db:
  image: postgres
  volumes:
    - ./pgdata:/var/lib/postgresql/data
web:
  image: alfredimage
  environment:
    - DATABASE_URL=postgres://postgres:mysecret@db:5432/alfred
  ports:
    - "3000:3000"
  links:
    - db